wandb_version: 1

a:
  desc: null
  value: 128
b:
  desc: null
  value: 64
c:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    code_path: code/training.py
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698712663.462967
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
out_layers:
  desc: null
  value:
  - 128
  - 64
  - 16
out_layers_activation:
  desc: null
  value: relu
conv_activation:
  desc: null
  value: relu
noise:
  desc: null
  value: 0
