wandb_version: 1

a:
  desc: null
  value: 64
b:
  desc: null
  value: 128
c:
  desc: null
  value: 1024
_wandb:
  desc: null
  value:
    code_path: code/training.py
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698711706.085514
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 7
      - 23
      - 37
      - 38
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch/epoch
      6:
      - 3
